import { normalizeTeam } from "@/lib/teams";

/** Canonical English team name → ISO 3166 code used by flagcdn. */
const EN_TO_ISO: Record<string, string> = {
  israel: "il",
  brazil: "br",
  argentina: "ar",
  france: "fr",
  germany: "de",
  spain: "es",
  england: "gb-eng",
  scotland: "gb-sct",
  wales: "gb-wls",
  ireland: "ie",
  portugal: "pt",
  italy: "it",
  netherlands: "nl",
  belgium: "be",
  croatia: "hr",
  uruguay: "uy",
  colombia: "co",
  switzerland: "ch",
  mexico: "mx",
  usa: "us",
  canada: "ca",
  japan: "jp",
  "south korea": "kr",
  australia: "au",
  morocco: "ma",
  senegal: "sn",
  ghana: "gh",
  nigeria: "ng",
  cameroon: "cm",
  egypt: "eg",
  tunisia: "tn",
  algeria: "dz",
  "ivory coast": "ci",
  poland: "pl",
  denmark: "dk",
  sweden: "se",
  norway: "no",
  serbia: "rs",
  austria: "at",
  turkey: "tr",
  greece: "gr",
  chile: "cl",
  peru: "pe",
  ecuador: "ec",
  paraguay: "py",
  venezuela: "ve",
  qatar: "qa",
  "saudi arabia": "sa",
  iran: "ir",
  iraq: "iq",
  "united arab emirates": "ae",
  ukraine: "ua",
  "czech republic": "cz",
  hungary: "hu",
  romania: "ro",
  slovakia: "sk",
  slovenia: "si",
  "costa rica": "cr",
  panama: "pa",
  honduras: "hn",
  jamaica: "jm",
  "new zealand": "nz",
};

/** Returns a real country flag URL for a team name (Hebrew or English), or null. */
export function flagUrl(teamName: string | null | undefined, width: 40 | 80 | 160 = 80): string | null {
  if (!teamName) return null;
  const iso = EN_TO_ISO[normalizeTeam(teamName)];
  return iso ? `https://flagcdn.com/w${width}/${iso}.png` : null;
}
